-- MySQL Script generated by MySQL Workbench
-- Wed Jun 28 21:51:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`p_tipoIdentificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`p_tipoIdentificacion` (
  `idtipoIdentificacion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `estadoRegistro` TINYINT(1) NULL,
  PRIMARY KEY (`idtipoIdentificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `identificacion` VARCHAR(45) NULL,
  `direccion` VARCHAR(255) NULL,
  `telefono` VARCHAR(45) NULL,
  `estadoRegistro` TINYINT(1) NOT NULL,
  `tipoIdentificacion_idtipoIdentificacion` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `tipoIdentificacion_idtipoIdentificacion`),
  UNIQUE INDEX `identificacion_UNIQUE` (`identificacion` ASC),
  INDEX `fk_usuario_tipoIdentificacion1_idx` (`tipoIdentificacion_idtipoIdentificacion` ASC),
  CONSTRAINT `fk_usuario_tipoIdentificacion1`
    FOREIGN KEY (`tipoIdentificacion_idtipoIdentificacion`)
    REFERENCES `mydb`.`p_tipoIdentificacion` (`idtipoIdentificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`p_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`p_rol` (
  `idp_rol` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `estadoRegistro` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idp_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarioRol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarioRol` (
  `idusuarioRol` INT NOT NULL AUTO_INCREMENT,
  `estadoRegistro` TINYINT(1) NULL,
  `usuario_idusuario` INT NOT NULL,
  `p_rol_idp_rol` INT NOT NULL,
  PRIMARY KEY (`idusuarioRol`, `usuario_idusuario`, `p_rol_idp_rol`),
  INDEX `fk_usuarioRol_usuario_idx` (`usuario_idusuario` ASC),
  INDEX `fk_usuarioRol_p_rol1_idx` (`p_rol_idp_rol` ASC),
  CONSTRAINT `fk_usuarioRol_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarioRol_p_rol1`
    FOREIGN KEY (`p_rol_idp_rol`)
    REFERENCES `mydb`.`p_rol` (`idp_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vehiculo` (
  `idvehiculo` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `referencia` VARCHAR(45) NULL,
  `cilindraje` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `estadoRegistro` TINYINT(1) NOT NULL,
  `fechaRegistro` DATETIME(1) NOT NULL,
  PRIMARY KEY (`idvehiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`p_comercial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`p_comercial` (
  `idp_comercial` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  `estadoRegistro` TINYINT(1) NOT NULL,
  `fechaRegistro` DATETIME(1) NULL,
  PRIMARY KEY (`idp_comercial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`p_metodoPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`p_metodoPago` (
  `idp_metodoPago` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `estadoRegistro` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idp_metodoPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`p_comoSeEntero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`p_comoSeEntero` (
  `idp_comoSeEntero` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `estadoRegistro` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idp_comoSeEntero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`p_tipoServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`p_tipoServicio` (
  `idp_tipoServicio` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `estadoRegistro` TINYINT(1) NOT NULL,
  `fechaRegistro` TIMESTAMP(1) NULL,
  PRIMARY KEY (`idp_tipoServicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicio` (
  `idservicio` INT NOT NULL AUTO_INCREMENT,
  `fechaInicioFormulario` DATETIME(1) NOT NULL,
  `otro` VARCHAR(255) NULL,
  `tratamiento` TINYINT NULL,
  `p_comercial_idp_comercial` INT NOT NULL,
  `p_metodoPago_idp_metodoPago` INT NOT NULL,
  `p_comoSeEntero_idp_comoSeEntero` INT NOT NULL,
  `p_tipoServicio_idp_tipoServicio` INT NOT NULL,
  `recomendacion` TINYINT NULL,
  `vehiculo_idvehiculo` INT NOT NULL,
  PRIMARY KEY (`idservicio`, `p_comercial_idp_comercial`, `p_metodoPago_idp_metodoPago`, `p_comoSeEntero_idp_comoSeEntero`, `p_tipoServicio_idp_tipoServicio`, `vehiculo_idvehiculo`),
  INDEX `fk_servicio_p_comercial1_idx` (`p_comercial_idp_comercial` ASC),
  INDEX `fk_servicio_p_metodoPago1_idx` (`p_metodoPago_idp_metodoPago` ASC),
  INDEX `fk_servicio_p_comoSeEntero1_idx` (`p_comoSeEntero_idp_comoSeEntero` ASC),
  INDEX `fk_servicio_p_tipoServicio1_idx` (`p_tipoServicio_idp_tipoServicio` ASC),
  INDEX `fk_servicio_vehiculo1_idx` (`vehiculo_idvehiculo` ASC),
  CONSTRAINT `fk_servicio_p_comercial1`
    FOREIGN KEY (`p_comercial_idp_comercial`)
    REFERENCES `mydb`.`p_comercial` (`idp_comercial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_p_metodoPago1`
    FOREIGN KEY (`p_metodoPago_idp_metodoPago`)
    REFERENCES `mydb`.`p_metodoPago` (`idp_metodoPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_p_comoSeEntero1`
    FOREIGN KEY (`p_comoSeEntero_idp_comoSeEntero`)
    REFERENCES `mydb`.`p_comoSeEntero` (`idp_comoSeEntero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_p_tipoServicio1`
    FOREIGN KEY (`p_tipoServicio_idp_tipoServicio`)
    REFERENCES `mydb`.`p_tipoServicio` (`idp_tipoServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_vehiculo1`
    FOREIGN KEY (`vehiculo_idvehiculo`)
    REFERENCES `mydb`.`vehiculo` (`idvehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`serviciosParaUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`serviciosParaUsuario` (
  `idserviciosParaUsuario` INT NOT NULL AUTO_INCREMENT,
  `estadoRegistro` TINYINT(1) NOT NULL,
  `fechaRegistro` DATETIME(1) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `servicio_idservicio` INT NOT NULL,
  PRIMARY KEY (`idserviciosParaUsuario`, `usuario_idusuario`, `servicio_idservicio`),
  INDEX `fk_serviciosParaUsuario_usuario1_idx` (`usuario_idusuario` ASC),
  INDEX `fk_serviciosParaUsuario_servicio1_idx` (`servicio_idservicio` ASC),
  CONSTRAINT `fk_serviciosParaUsuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serviciosParaUsuario_servicio1`
    FOREIGN KEY (`servicio_idservicio`)
    REFERENCES `mydb`.`servicio` (`idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehiculoPorUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vehiculoPorUsuario` (
  `idvehiculoPorUsuario` INT NOT NULL AUTO_INCREMENT,
  `estadoRegistro` TINYINT(1) NULL,
  `fechaRegistro` DATETIME(1) NOT NULL,
  `vehiculo_idvehiculo` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idvehiculoPorUsuario`, `vehiculo_idvehiculo`, `usuario_idusuario`),
  INDEX `fk_vehiculoPorUsuario_vehiculo1_idx` (`vehiculo_idvehiculo` ASC),
  INDEX `fk_vehiculoPorUsuario_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_vehiculoPorUsuario_vehiculo1`
    FOREIGN KEY (`vehiculo_idvehiculo`)
    REFERENCES `mydb`.`vehiculo` (`idvehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculoPorUsuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarioCredenciales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarioCredenciales` (
  `idusuarioCredenciales` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `estadoRegistro` TINYINT(1) NOT NULL,
  `fechaRegistro` DATETIME(1) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idusuarioCredenciales`, `usuario_idusuario`),
  INDEX `fk_usuarioCredenciales_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_usuarioCredenciales_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`p_estadoServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`p_estadoServicio` (
  `idp_estadoServicio` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `estadoRegistro` TINYINT(1) NOT NULL,
  `fechaRegistro` DATETIME(1) NOT NULL,
  PRIMARY KEY (`idp_estadoServicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estadoServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estadoServicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estadoRegistro` TINYINT(1) NOT NULL,
  `fechaRegistro` DATETIME(1) NOT NULL,
  `idp_estadoservicio` INT NOT NULL,
  `idservicio` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`id`, `idp_estadoservicio`, `idservicio`, `usuario_idusuario`),
  INDEX `fk_estadoServicio_p_estadoServicio1_idx` (`idp_estadoservicio` ASC),
  INDEX `fk_estadoServicio_servicio1_idx` (`idservicio` ASC),
  INDEX `fk_estadoServicio_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_estadoServicio_p_estadoServicio1`
    FOREIGN KEY (`idp_estadoservicio`)
    REFERENCES `mydb`.`p_estadoServicio` (`idp_estadoServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estadoServicio_servicio1`
    FOREIGN KEY (`idservicio`)
    REFERENCES `mydb`.`servicio` (`idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estadoServicio_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`datosDelServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datosDelServicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fechaInicioServicio` DATETIME(1) NULL,
  `asignado` VARCHAR(100) NULL,
  `operador` VARCHAR(45) NULL,
  `imei` VARCHAR(45) NULL,
  `linea` VARCHAR(45) NULL,
  `renovacion` VARCHAR(45) NULL,
  `fechaRenovacion` DATETIME(1) NULL,
  `recarga` VARCHAR(45) NULL,
  `fechaRecarga` DATETIME(1) NULL,
  `instalacion` VARCHAR(45) NULL,
  `instalador` VARCHAR(100) NULL,
  `valorInstalacion` VARCHAR(45) NULL,
  `pagoInstalacion` VARCHAR(45) NULL,
  `valorVenta` VARCHAR(45) NULL,
  `medotoPago` VARCHAR(45) NULL,
  `realizarFactura` VARCHAR(45) NULL,
  `manejo` VARCHAR(45) NULL,
  `ingresoPago` VARCHAR(45) NULL,
  `remision` VARCHAR(45) NULL,
  `facturaNumero` VARCHAR(45) NULL,
  `actualizacion` VARCHAR(100) NULL,
  `estadoRegistro` TINYINT(1) NULL,
  `fechaRegistro` DATETIME(1) NULL,
  `servicio_idservicio` INT NOT NULL,
  PRIMARY KEY (`id`, `servicio_idservicio`),
  INDEX `fk_datosDelServicio_servicio1_idx` (`servicio_idservicio` ASC),
  CONSTRAINT `fk_datosDelServicio_servicio1`
    FOREIGN KEY (`servicio_idservicio`)
    REFERENCES `mydb`.`servicio` (`idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
